apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  postgres-user: cG9zdGdyZXM=
  postgres-pass: cG9zdGdyZXM=